### ISSUE TITLE
"Tiny Scheme" name already in use

### ISSUE THREAD

**Issue by johnwcowan** [jrincayc/r7rs-pico-spec#1]
There is an interpreter named [TinyScheme](http://tinyscheme.sourceforge.net/home.html) that implements a subset of R5RS .  In order to avoid confusion, this spec should be given a different name.  To avoid collisions, check the [fairly complete list](http://community.schemewiki.org/?Scheme-FAQ-Standards#H-19kqio1) of Schemes.

**Comment by jrincayc** [comment]
Hm, Mini and Nano seem to be available.

**Comment by jrincayc** [comment]
Hm, based on a google search, pico scheme seems to be the only one that has not been used.

**Comment by jrincayc** [comment]
Besides merging in #3, also need to change name of repository, and add an empty repository at https://github.com/jrincayc/r7rs-tiny-spec with a readme that points people to https://github.com/jrincayc/r7rs-pico-spec

**Comment by hga** [comment]
While you're at it it would be more convenient if the main branch was named the common "master."  The "main" you like to use is unambiguous, but an exception to a lot of standard workflows.

**Comment by jrincayc** [comment]
> While you're at it it would be more convenient if the main branch was named the common "master." The "main" you like to use is unambiguous, but an exception to a lot of standard workflows.

Hm, main is actually the default now for github.

**Comment by jrincayc** [comment]
Merged in #3, and https://github.com/jrincayc/r7rs-tiny-spec points to pico.
