### ISSUE TITLE
eqv? instead of eq?

### ISSUE THREAD

**Issue by johnwcowan** [jrincayc/r7rs-pico-spec#10]
The `eqv?` procedure is Scheme's identity function, whereas `eq?` is basically a speed hack that is allowed to say "I don't know" in more cases.  I suggest that you switch Pico-R7RS to providing `eqv?`, which will return `#t` instead of an unspecified boolean on numbers that are `-`.

**Comment by jrincayc** [comment]
This is a simple enough change to the specification, and implementing it is basically one more case than `eq?` so I will make it.  Thanks for the suggestion.

**Comment by jrincayc** [comment]
@johnwcowan  I created a pull request for this.
