### ISSUE TITLE
named let

### ISSUE THREAD

**Issue by johnwcowan** [jrincayc/r7rs-pico-spec#11]
Consider adding named `let` to the language.  It lets you iterate over lists nicely.

**Comment by jrincayc** [comment]
Hm, in r7rs small section 7.3, the named `let` syntax-rules use `letrec`, and the `letrec` syntax-rules use `set!`, so I am wondering how hard it would be implement named `let` without using `set!`. (Since we have `define` inside of `lambda`'s possibly not that hard.)

**Comment by johnwcowan** [comment]
I think you might need to treat named `let` as primitive.  The implementation of `letrec` given in R[567]RS depends on a gimmick, really.

**Comment by jrincayc** [comment]
I think my answer to this is leaning towards no, but I will try translating an example named `let` into `lambda`s, unnamed `let`s and `define`'s and see how complicated it becomes.

**Comment by jrincayc** [comment]
And thank you for commenting on pico scheme and suggesting things to add. I do have a fairly high threshold to add anything, so I apologize for leaning towards saying no.

**Comment by jrincayc** [comment]
Hm, the example in r7rs:
```lisp
(let loop ((numbers '(3 -2 1 6 -5))
	   (nonneg '())
	   (neg '()))
     (cond ((null? numbers) (list nonneg neg))
	   ((>= (car numbers) 0)
	    (loop (cdr numbers)
		  (cons (car numbers) nonneg)
		  neg))
	   ((< (car numbers) 0)
	    (loop (cdr numbers)
		  nonneg
		  (cons (car numbers) neg)))))
```
can be translated into:
```lisp
(let ((numbers '(3 -2 1 6 -5))
      (nonneg '())
      (neg '()))
  (define loop (lambda (numbers nonneg neg)
	       (cond ((null? numbers) (list nonneg neg))
		     ((>= (car numbers) 0)
		      (loop (cdr numbers)
			    (cons (car numbers) nonneg)
			    neg))
		     ((< (car numbers) 0)
		      (loop (cdr numbers)
			    nonneg
			    (cons (car numbers) neg))))))
  (loop numbers nonneg neg))
```
and since pico scheme doesn't have >= this is:
```lisp
(let ((numbers '(3 -2 1 6 -5))
      (nonneg '())
      (neg '()))
  (define loop (lambda (numbers nonneg neg)
	       (cond ((null? numbers) (list nonneg neg))
		     ((or (> (car numbers) 0) (= (car numbers) 0))
		      (loop (cdr numbers)
			    (cons (car numbers) nonneg)
			    neg))
		     ((< (car numbers) 0)
		      (loop (cdr numbers)
			    nonneg
			    (cons (car numbers) neg))))))
  (loop numbers nonneg neg))
```

**Comment by jrincayc** [comment]
I would be happy to add the pico scheme equivalent as an example in the examples section.

**Comment by jrincayc** [comment]
Closing since I think regular let is sufficient.
