### ISSUE TITLE
include

### ISSUE THREAD

**Issue by johnwcowan** [jrincayc/r7rs-pico-spec#13]
Providing `include` allows modularization of Pico programs: in particular, you can load one or more libraries.

**Comment by jrincayc** [comment]
I agree this would be useful, but among other things, it requires string literals and an explanation of what read does to be added to the specification, so I think my answer for this is no.

**Comment by johnwcowan** [comment]
It can be done as a REPL command rather than a Scheme expression.

**Comment by jrincayc** [comment]
Hm, implementing it would involve additional code in both the lexer and the parser, and involve adding more to the syntax and description, so my conclusion on this request is no since it adds more complexity.  Thank you for the suggestion.
