### ISSUE TITLE
improve number specification

### ISSUE THREAD

**Issue by jobol** [jrincayc/r7rs-pico-spec#24]
chapter 6.2:

> Pico Scheme implementations should support integers suf-
> ficiently large to calculate the length of any allowable list,
> and for binary computers that usually can be satisfied by
> signed integers of the same bit length as machine addresses.

Implementations could use pointer tagging techniques.

Also, some rare hardware have different length between pointers and numbers.

In both cases, satisfying the second part of the spec is an issue. I suggest to remove it.

I also suggest to explain a bit more how overflow are treated. There is no error reporting and the numbers are told to be of limited then something as to be told. My suggest? Stay simple: [1] signed integers (no unsigned) [2] explicit it wraps around.

**Comment by jobol** [comment]
The words used for R7RS are good except that vectors, bytevectors and strings aren't in pico R7RS.

**Comment by jrincayc** [comment]
So how about:
Pico Scheme implementations should support signed integers with a range that includes the longest possible list length. 

Looking at R7RS, it looks like implementations adding too big of integers should either error or coerce it to a float with a greater range. 

6.2.3 "If one of these procedures is unable to deliver an exact result when given exact arguments, then it may either report a
violation of an implementation restriction or it may silently coerce its result to an inexact number; such a coercion can cause an error later."

I suppose two possible ways of dealing with this in Pico Scheme for implementations that only support finite integers would be wraparound or returning something that returns `#f` from `number?`  I could add a note for this, or just leave it unsaid.

**Comment by jobol** [comment]
Returning #f instead of a number might finally offer a good solution.
It also solve the error case of numeric operation on  things that are not numbers: it could be said that it returns #f.

**Comment by jrincayc** [comment]
Proposed new text (I will probably edit this a bit, but this is one way I am thinking of modifying it):
```tex
Pico Scheme implementations should support signed integers with a
range that includes the longest possible list length.

\begin{note}
Pico Scheme implementations may support integers of practically
unlimited size, or they may support integers with a limited range.  If
using limited range integers some operations may overflow. Pico Scheme
implementations should document integer range restrictions and how
they are handeled. Pico Scheme implementations may either return the
wrapped around number, or return a miscellaneous value (such as {\it
  false} or {\it undefined}) for overflow.
\end{note}
```
In branch: https://github.com/jrincayc/r7rs-pico-spec/tree/fix_24_numbers

**Comment by jobol** [comment]
nice, I'm voting for

**Comment by jrincayc** [comment]
I updated the text a bit, and created a pull request.

**Comment by jrincayc** [comment]
One more question, is "José Bollo" the correct name for me to use in the acknowledgements?

**Comment by jobol** [comment]
It is my name yes

**Comment by jrincayc** [comment]
Okay, thanks for the suggestion, I have merged a fix.
